domains                  = "dominic.f5training2.cloud"
name                     = "dominic"
namespace                = "dominic"
origin_pool_service_name = "boutique-frontend.dominic"
origin_pool_virtual_site = "dominic-vsite"
